### ISSUE TITLE
App names should be word wrapped rather than wrap anywhere

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#33]
[Here](https://i.imgur.com/7yTFwIb.png) is a screenshot where app names are wrapping anywhere and in some cases it makes it difficult to read the name. Since they are proper nouns they should word wrap in my opinion.

And in some edge cases where the names are longer than 2 lines, you should elide them. This way the app doesn't take up way too much space.

**Comment by bhdouglass** [comment]
Unfortunately there are issues without word wrapping... Things overrunning each other, etc. See issue #29.

I think I'm going to experiment with other options, like making the font smaller.

Can you take a screenshot from your phone of the same view? The screenshot you've attached _should_ be expanded more, so that's probably already a bug.

**Comment by krnekhelesh** [comment]
On the phone, it looks much better.
![newapps](https://cloud.githubusercontent.com/assets/761845/7539120/fc84a422-f5a4-11e4-8969-5cb0b6f87587.png)

**Comment by bhdouglass** [comment]
Ok good, my smaller font size seems to be working. I'll close this out for now.
